export interface CountryInfo {
  name: string;
  code: string;
  currency: string;
  currencySymbol: string;
  currencyName: string;
  flag: string;
}

// Exchange rates relative to USD (1 unit of currency = X USD)
export const exchangeRates: Record<string, number> = {
  USD: 1.0,
  EUR: 1.09,
  GBP: 1.27,
  JPY: 0.0067,
  CAD: 0.74,
  AUD: 0.65,
  CHF: 1.12,
  CNY: 0.138,
  INR: 0.012,
  MXN: 0.058,
  BRL: 0.2,
  KRW: 0.00074,
  SGD: 0.74,
  HKD: 0.128,
  NOK: 0.095,
  SEK: 0.096,
  DKK: 0.146,
  NZD: 0.61,
  ZAR: 0.054,
  AED: 0.272,
  SAR: 0.266,
  QAR: 0.274,
  KWD: 3.26,
  BHD: 2.65,
  OMR: 2.6,
  PKR: 0.0036,
  BDT: 0.0091,
  IDR: 0.000063,
  MYR: 0.224,
  PHP: 0.018,
  THB: 0.028,
  VND: 0.000039,
  EGP: 0.032,
  NGN: 0.00066,
  KES: 0.0077,
  GHS: 0.068,
  TZS: 0.00039,
  UGX: 0.00027,
  ETB: 0.0177,
  MAD: 0.099,
  TND: 0.32,
  RUB: 0.011,
  TRY: 0.031,
  PLN: 0.25,
  CZK: 0.044,
  HUF: 0.0028,
  RON: 0.22,
  UAH: 0.024,
  ILS: 0.27,
  CLP: 0.0011,
  COP: 0.00024,
  PEN: 0.27,
  ARS: 0.001,
};

export const countries: CountryInfo[] = [
  { name: "United States", code: "US", currency: "USD", currencySymbol: "$", currencyName: "US Dollar", flag: "🇺🇸" },
  { name: "United Kingdom", code: "GB", currency: "GBP", currencySymbol: "£", currencyName: "British Pound", flag: "🇬🇧" },
  { name: "European Union", code: "EU", currency: "EUR", currencySymbol: "€", currencyName: "Euro", flag: "🇪🇺" },
  { name: "Germany", code: "DE", currency: "EUR", currencySymbol: "€", currencyName: "Euro", flag: "🇩🇪" },
  { name: "France", code: "FR", currency: "EUR", currencySymbol: "€", currencyName: "Euro", flag: "🇫🇷" },
  { name: "Italy", code: "IT", currency: "EUR", currencySymbol: "€", currencyName: "Euro", flag: "🇮🇹" },
  { name: "Spain", code: "ES", currency: "EUR", currencySymbol: "€", currencyName: "Euro", flag: "🇪🇸" },
  { name: "Japan", code: "JP", currency: "JPY", currencySymbol: "¥", currencyName: "Japanese Yen", flag: "🇯🇵" },
  { name: "Canada", code: "CA", currency: "CAD", currencySymbol: "C$", currencyName: "Canadian Dollar", flag: "🇨🇦" },
  { name: "Australia", code: "AU", currency: "AUD", currencySymbol: "A$", currencyName: "Australian Dollar", flag: "🇦🇺" },
  { name: "Switzerland", code: "CH", currency: "CHF", currencySymbol: "Fr", currencyName: "Swiss Franc", flag: "🇨🇭" },
  { name: "China", code: "CN", currency: "CNY", currencySymbol: "¥", currencyName: "Chinese Yuan", flag: "🇨🇳" },
  { name: "India", code: "IN", currency: "INR", currencySymbol: "₹", currencyName: "Indian Rupee", flag: "🇮🇳" },
  { name: "Mexico", code: "MX", currency: "MXN", currencySymbol: "Mex$", currencyName: "Mexican Peso", flag: "🇲🇽" },
  { name: "Brazil", code: "BR", currency: "BRL", currencySymbol: "R$", currencyName: "Brazilian Real", flag: "🇧🇷" },
  { name: "South Korea", code: "KR", currency: "KRW", currencySymbol: "₩", currencyName: "South Korean Won", flag: "🇰🇷" },
  { name: "Singapore", code: "SG", currency: "SGD", currencySymbol: "S$", currencyName: "Singapore Dollar", flag: "🇸🇬" },
  { name: "Hong Kong", code: "HK", currency: "HKD", currencySymbol: "HK$", currencyName: "Hong Kong Dollar", flag: "🇭🇰" },
  { name: "Norway", code: "NO", currency: "NOK", currencySymbol: "kr", currencyName: "Norwegian Krone", flag: "🇳🇴" },
  { name: "Sweden", code: "SE", currency: "SEK", currencySymbol: "kr", currencyName: "Swedish Krona", flag: "🇸🇪" },
  { name: "Denmark", code: "DK", currency: "DKK", currencySymbol: "kr", currencyName: "Danish Krone", flag: "🇩🇰" },
  { name: "New Zealand", code: "NZ", currency: "NZD", currencySymbol: "NZ$", currencyName: "New Zealand Dollar", flag: "🇳🇿" },
  { name: "South Africa", code: "ZA", currency: "ZAR", currencySymbol: "R", currencyName: "South African Rand", flag: "🇿🇦" },
  { name: "UAE", code: "AE", currency: "AED", currencySymbol: "د.إ", currencyName: "UAE Dirham", flag: "🇦🇪" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", currencySymbol: "﷼", currencyName: "Saudi Riyal", flag: "🇸🇦" },
  { name: "Qatar", code: "QA", currency: "QAR", currencySymbol: "﷼", currencyName: "Qatari Riyal", flag: "🇶🇦" },
  { name: "Kuwait", code: "KW", currency: "KWD", currencySymbol: "د.ك", currencyName: "Kuwaiti Dinar", flag: "🇰🇼" },
  { name: "Bahrain", code: "BH", currency: "BHD", currencySymbol: "BD", currencyName: "Bahraini Dinar", flag: "🇧🇭" },
  { name: "Pakistan", code: "PK", currency: "PKR", currencySymbol: "₨", currencyName: "Pakistani Rupee", flag: "🇵🇰" },
  { name: "Bangladesh", code: "BD", currency: "BDT", currencySymbol: "৳", currencyName: "Bangladeshi Taka", flag: "🇧🇩" },
  { name: "Indonesia", code: "ID", currency: "IDR", currencySymbol: "Rp", currencyName: "Indonesian Rupiah", flag: "🇮🇩" },
  { name: "Malaysia", code: "MY", currency: "MYR", currencySymbol: "RM", currencyName: "Malaysian Ringgit", flag: "🇲🇾" },
  { name: "Philippines", code: "PH", currency: "PHP", currencySymbol: "₱", currencyName: "Philippine Peso", flag: "🇵🇭" },
  { name: "Thailand", code: "TH", currency: "THB", currencySymbol: "฿", currencyName: "Thai Baht", flag: "🇹🇭" },
  { name: "Egypt", code: "EG", currency: "EGP", currencySymbol: "£", currencyName: "Egyptian Pound", flag: "🇪🇬" },
  { name: "Nigeria", code: "NG", currency: "NGN", currencySymbol: "₦", currencyName: "Nigerian Naira", flag: "🇳🇬" },
  { name: "Kenya", code: "KE", currency: "KES", currencySymbol: "KSh", currencyName: "Kenyan Shilling", flag: "🇰🇪" },
  { name: "Russia", code: "RU", currency: "RUB", currencySymbol: "₽", currencyName: "Russian Ruble", flag: "🇷🇺" },
  { name: "Turkey", code: "TR", currency: "TRY", currencySymbol: "₺", currencyName: "Turkish Lira", flag: "🇹🇷" },
  { name: "Poland", code: "PL", currency: "PLN", currencySymbol: "zł", currencyName: "Polish Zloty", flag: "🇵🇱" },
  { name: "Israel", code: "IL", currency: "ILS", currencySymbol: "₪", currencyName: "Israeli Shekel", flag: "🇮🇱" },
  { name: "Chile", code: "CL", currency: "CLP", currencySymbol: "$", currencyName: "Chilean Peso", flag: "🇨🇱" },
  { name: "Colombia", code: "CO", currency: "COP", currencySymbol: "$", currencyName: "Colombian Peso", flag: "🇨🇴" },
  { name: "Peru", code: "PE", currency: "PEN", currencySymbol: "S/", currencyName: "Peruvian Sol", flag: "🇵🇪" },
  { name: "Argentina", code: "AR", currency: "ARS", currencySymbol: "$", currencyName: "Argentine Peso", flag: "🇦🇷" },
  { name: "Vietnam", code: "VN", currency: "VND", currencySymbol: "₫", currencyName: "Vietnamese Dong", flag: "🇻🇳" },
  { name: "Morocco", code: "MA", currency: "MAD", currencySymbol: "MAD", currencyName: "Moroccan Dirham", flag: "🇲🇦" },
  { name: "Ethiopia", code: "ET", currency: "ETB", currencySymbol: "Br", currencyName: "Ethiopian Birr", flag: "🇪🇹" },
];

export function getCountryByCurrency(currency: string): CountryInfo | undefined {
  return countries.find((c) => c.currency === currency);
}

export function convertCurrency(
  amount: number,
  fromCurrency: string,
  toCurrency: string
): number {
  const fromRate = exchangeRates[fromCurrency] ?? 1;
  const toRate = exchangeRates[toCurrency] ?? 1;
  return amount * (fromRate / toRate);
}

export const EXPENSE_CATEGORIES = [
  "Travel & Transportation",
  "Meals & Entertainment",
  "Accommodation",
  "Office Supplies",
  "Software & Technology",
  "Training & Education",
  "Marketing & Advertising",
  "Utilities",
  "Professional Services",
  "Healthcare",
  "Equipment",
  "Communication",
  "Other",
];

export const ALL_CURRENCIES = [
  { code: "USD", symbol: "$", name: "US Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "GBP", symbol: "£", name: "British Pound" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "CAD", symbol: "C$", name: "Canadian Dollar" },
  { code: "AUD", symbol: "A$", name: "Australian Dollar" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "MXN", symbol: "Mex$", name: "Mexican Peso" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar" },
  { code: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "DKK", symbol: "kr", name: "Danish Krone" },
  { code: "NZD", symbol: "NZ$", name: "New Zealand Dollar" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "EGP", symbol: "£", name: "Egyptian Pound" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty" },
  { code: "ILS", symbol: "₪", name: "Israeli Shekel" },
];
